# Generated by Django 5.1.3 on 2024-12-29 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_initial'),
        ('teacher_app', '0004_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(default='0000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrolled_classes',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='teacher_app.class'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
